"""Read and write /etc/cryptsetup-beep/config.

The on-disk format is POSIX shell key=value, sourced by play-beep.sh.
Allowed keys are whitelisted both for forward-compatibility and as a defence
when --write-config validates a staging file before moving it to /etc.
"""

from __future__ import annotations

import os
import re
import shlex
from dataclasses import dataclass, field, fields
from pathlib import Path

CONFIG_PATH = Path("/etc/cryptsetup-beep/config")
STAGING_PATH = Path("/run/cryptsetup-beep-staging.config")

ALLOWED_KEYS = frozenset({
    "METHOD",
    "CODEC_MATCH",
    "CODEC_MODULES",
    "PCM_DEVICE",
    "MIXER_MASTER",
    "MIXER_SPEAKER",
    "MIXER_HEADPHONE",
    "MIXER_PCM",
    "BEEP_WAV",
    "PCSPKR_FREQ",
    "PCSPKR_LEN",
})

# Conservative regex for shell-safe values: alphanum, common punctuation,
# spaces inside quotes. Reject anything that could be code injection if the
# value got eval'd by the shell.
_VALUE_RE = re.compile(r"^[A-Za-z0-9_\-\.\,\:\=\%\/\+\s]*$")


@dataclass
class BeepConfig:
    method: str = "alsa"  # "alsa" or "pcspkr"
    codec_match: str = ""
    codec_modules: str = ""  # space-separated list, kept as a single string
    pcm_device: int = 0
    mixer_master: str = "82%,on"
    mixer_speaker: str = "100%,on"
    mixer_headphone: str = "70%,on"
    mixer_pcm: str = "100%"
    beep_wav: str = "/usr/share/cryptsetup-beep/beep.wav"
    pcspkr_freq: int = 440
    pcspkr_len: int = 500

    @classmethod
    def from_file(cls, path: Path = CONFIG_PATH) -> "BeepConfig":
        if not path.exists():
            return cls()
        data = _parse_shell_kv(path.read_text())
        return cls.from_dict(data)

    @classmethod
    def from_dict(cls, data: dict[str, str]) -> "BeepConfig":
        kwargs: dict[str, object] = {}
        # snake_case → SHELL_CASE map for fields
        for f in fields(cls):
            shell_key = f.name.upper()
            if shell_key in data:
                value = data[shell_key]
                if f.type is int or f.type == "int":
                    try:
                        kwargs[f.name] = int(value)
                    except ValueError:
                        pass
                else:
                    kwargs[f.name] = value
        return cls(**kwargs)  # type: ignore[arg-type]

    def to_shell(self) -> str:
        lines = ["# Generated by cryptsetup-beep --init", ""]
        for f in fields(self):
            shell_key = f.name.upper()
            value = getattr(self, f.name)
            if isinstance(value, int):
                lines.append(f"{shell_key}={value}")
            else:
                # Always quote strings — robust for spaces, percents etc.
                lines.append(f"{shell_key}={shlex.quote(value)}")
        return "\n".join(lines) + "\n"

    def write_staging(self, path: Path = STAGING_PATH) -> Path:
        path.write_text(self.to_shell())
        os.chmod(path, 0o644)
        return path


def validate(data: dict[str, str]) -> list[str]:
    """Return a list of error strings; empty list means valid."""
    errors: list[str] = []
    for key, value in data.items():
        if key not in ALLOWED_KEYS:
            errors.append(f"unknown key: {key}")
            continue
        if not _VALUE_RE.match(value):
            errors.append(f"unsafe characters in {key}")
    method = data.get("METHOD", "")
    if method and method not in ("alsa", "pcspkr"):
        errors.append(f"METHOD must be 'alsa' or 'pcspkr', got {method!r}")
    return errors


def _parse_shell_kv(text: str) -> dict[str, str]:
    """Parse a tiny subset of shell: KEY=VALUE lines, with shell quoting.

    Comments (# ...) and blank lines are ignored. Multi-line values are not
    supported. Values are unquoted via shlex with POSIX rules.
    """
    out: dict[str, str] = {}
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        if not key.isidentifier() and not re.match(r"^[A-Z_][A-Z0-9_]*$", key):
            continue
        # shlex.split handles quotes correctly; we keep the first token
        try:
            tokens = shlex.split(value, posix=True)
        except ValueError:
            continue
        out[key] = tokens[0] if tokens else ""
    return out
